name: Manual release

on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Name of version  (Prerelease xx)'
        required: true
      versionTag:
        description: 'Version number (vx.x.x)'
        required: true

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x

    - uses: actions/cache@v2
      with:
        path: |
          ~/go/pkg/mod          # Module download cache
          ~/.cache/go-build     # Build cache (Linux)
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
          
    - name: Build
      run: |
        GOOS=darwin GOARCH=amd64 go build -v -o ping-avg_${{ github.event.inputs.versionTag }}_macos main.go
        GOOS=linux GOARCH=amd64 go build -v -o ping-avg_${{ github.event.inputs.versionTag }}_linux-x64 main.go

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        draft: true
        title: ${{ github.event.inputs.versionName }}
        files: |
          ping-avg*